### ISSUE TITLE
Microstuttering Dragonflight Prepatch

### ISSUE THREAD

**Issue by dieterdanger** [int3ro/Nameplates_Threat#23]
Hello,
thanks for your wonderful addon. However, since Dragonflight prepatch I get microstuttering when this addon is enabled. There are no further error messages shown.

Does anyone else have these kind of problems? If so, Is there any way to fix this problem?

Best regards
Dennis

**Comment by mikfhan** [comment]
I'm working on another issue on curseforge with lots of script errors while friendly player nameplates are visible, maybe it's those script errors underneath giving the stutters. Could you try turning friendly nameplates on/off in the blizzard settings and see if there's a difference?

Try also to disable "Color Gradient Updates Per Second" in the addon settings, that one has the addon run x times every second instead of only running whenever one of the mobs' threat target changes, might reduce stuttering then, but this one has been in place for many addon versions and Classic also, so if the stutter only happens for Dragonflight prepatch/retail it might rather be the thing I mentioned up top.

**Comment by mikfhan** [comment]
I got pretty smooth frametimes with all Radeon Chill + FrameRate Target Control + EnhancedSync/Vsync disabled in AMD graphics/driver settings, and likewise no Vsync/framelimits in WoW client or RivaTuner, maybe try writing /console scriptErrors 1 into chat, to see if there were AddOn bugs/errors not shown that cause the microstutters. I had to disable a LOT of powersaving options in RTSS and AMD settings then Alt+Enter / restart WoW and RTSS a few times before their framelimiters actually stopped interfering :D

Sometimes I've also used the AddonUsage addon, then just typing /addonusage in chat, to measure CPU and memory use from addons. You could try disabling all other addons, then if still stuttering, try overwriting your NamePlatesThreat.lua file with the one from issue above, it should fix those friendly nameplate bugs that kept spamming script errors while friendly nameplates in a group were visible.

![image](https://user-images.githubusercontent.com/13070562/199804919-1c466dbd-c21e-4233-ba1d-b966d5c9ae77.png)

**Comment by dieterdanger** [comment]
Hey mikfhan,
sorry for not replying earlier. I thought github would notify me via email.

If I disable friendly nameplates, microstuttering goes away. Disabling"Color Gradient Updates Per Second" had no positive effect.

After these initial tests I replaced the file NamePlatesThreat.lua with the one from https://www.curseforge.com/wow/addons/blizzard-nameplates-threat/issues/10. With these updated file microstuttering is gone even with friendly nameplates enabled!

So thanks for your help and keep on doing you wonderful work on this addon!

Best regards
