### ISSUE TITLE
Never seen red nameplates

### ISSUE THREAD

**Issue by gabbsmo** [int3ro/Nameplates_Threat#28]
First, thanks for excellent addon. Adds valuable information without adding clutter to the UI. I just wonder if I am using it wrong or it is actually a bug.

According to the description nameplates should turn red when healer have high threat. I have been tanking with the addon since Scarlet Monastery through LBRS and have not seen that once, not even if healer has aggro. I play on Classic Era.

**Comment by gabbsmo** [comment]
Ok I understand that there's a limitation in Classic Era.

Personally I like the idea of using the combat log. People don't always play according to class and specc, especially in era where there's no dual specc. 

If it computationally expensive, maybe it's good enough to calculate this once per instance or party members change.

**Comment by mikfhan** [comment]
Alright, I have a first attempt of doing this now. Maybe you can help test it, since it only works when in a party/raid :)

You can download the latest NamePlatesThreat.lua from link below, then overwrite your current one in your addon folder:
https://github.com/int3ro/Nameplates_Threat/raw/mikfhan/NamePlatesThreat.lua

It scans the combat log and whenever a group member cast a healing spell (or heal over time ticks some healing) it adds that group member to a list of healer candidates, with the timestamp of their latest healing. Directly after this, anyone on the list newer than 60 seconds goes into the "HEALER" role, and anyone older goes back in the "DAMAGER" role. Group leaders and raid maintanks/assist are kept in the "TANK" role always, so you have to test this when the potential healer is not the group leader or raid maintank/assist. Do tell if it works or not :) and remember you MUST be in a group for it to work.

Afterwards perhaps we two could even test it directly (or if there's something broken/unclear) on the "Classic Era PTR 3" realm (I don't have an active WoW subscription so all addon testing I do has to be via PTR servers sadly). Only if our timezones align of course - I am CET timezone, and can try to be online from 18:00 to 23:00 or so on workdays and weekends (level 1 night elf druid Mikfhan in starting area, maybe you could make one also and post your timezone/online times, then ingame whisper me from the /who panel right-click if you see me online).

**Comment by gabbsmo** [comment]
I can test this in some next time I tank dungeon. Will let you know if there are any issues.

**Comment by mikfhan** [comment]
Super, I just now 18:45 CET pushed a small CPU improvement to the same raw-file so you may want to redownload it from the link above before testing then /reload in chat after overwriting the lua file. And remember, you have to be group leader in the party to be detected as tank, or be assigned one of the maintank/assist roles in a raid.

**Comment by gabbsmo** [comment]
I have not forgotten about this, just have not been the tank in a dungeon group for a while. The green nameplates seem to work as they should, as well as yellow and gray but that was also the case before.

I have seen red bars. In one group it was red even if a hunter was the target. Could that be a bug? Maybe pet healing could have something to do with it.

**Comment by mikfhan** [comment]
No rush, and good find! Indeed a bug - I've updated latest file above so now it should only count healers if they cast on another player (not themselves, and not pets) - you should be able to retest this even as a damager role if that's easier to find groups.

**Comment by gabbsmo** [comment]
Thanks! Just tested and now it seems to behave like I expect it to. Great work!

**Comment by gabbsmo** [comment]
I do get a prompt sometimes about addons causing errors. I suspect it might be your addon since it only happens in dungeons. I have installed BugGrabber and BugSack. Will report back when I have more information.

**Comment by gabbsmo** [comment]
Here is what BugGrabber collected:

```
2x ...terface\AddOns\NamePlatesThreat\NamePlatesThreat-3.2.lua:739: bad argument #2 to 'remove' (number expected, got string)
[string "=[C]"]: in function `remove'
[string "@Interface\AddOns\NamePlatesThreat\NamePlatesThreat-3.2.lua"]:739: in function <...terface\AddOns\NamePlatesThreat\NamePlatesThreat.lua:661>

Locals:
(*temporary) = <table> {
 1 = "party1"
 2 = "party1"
 3 = "party1"
 4 = "party1"
 5 = "party1"
 6 = "party1"
 7 = "party1"
 8 = "party1"
 9 = "party1"
 10 = "party1"
 11 = "party1"
 12 = "party1"
 13 = "party1"
 14 = "party1"
 15 = "party1"
 16 = "party1"
 17 = "party1"
 18 = "party1"
 19 = "party1"
 20 = "party1"
 21 = "party1"
 22 = "party1"
 23 = "party1"
 24 = "party1"
 25 = "party1"
 26 = "party1"
 27 = "party1"
 28 = "party1"
 29 = "party1"
 30 = "party2"
 31 = "party2"
 32 = "party2"
 33 = "party2"
 34 = "party2"
 35 = "party2"
 36 = "party2"
 37 = "party2"
 38 = "party2"
 39 = "party1"
 40 = "party2"
 41 = "party2"
 42 = "party1"
 43 = "party1"
 44 = "party1"
 45 = "party1"
 46 = "party1"
 47 = "party1"
 48 = "party1"
 49 = "party1"
 50 = "party1"
 51 = "party1"
 52 = "party1"
 53 = "party1"
 54 = "party1"
 55 = "party1"
 56 = "party1"
 57 = "party1"
 58 = "party1"
 59 = "party1"
}
(*temporary) = "party2"
(*temporary) = "number expected, got string"
```

```
491x ...terface\AddOns\NamePlatesThreat\NamePlatesThreat-3.2.lua:720: bad argument #2 to 'remove' (number expected, got string)
[string "=[C]"]: in function `remove'
[string "@Interface\AddOns\NamePlatesThreat\NamePlatesThreat-3.2.lua"]:720: in function <...terface\AddOns\NamePlatesThreat\NamePlatesThreat.lua:661>

Locals:
(*temporary) = <table> {
 1 = "party1"
 2 = "party2"
 3 = "party3"
 4 = "party4"
}
(*temporary) = "party1"
(*temporary) = "number expected, got string"
```

**Comment by gabbsmo** [comment]
Also saw red plates on a rouge today. Not sure what the reason could have been. Healing potions?

**Comment by gabbsmo** [comment]
Tested tanking today and there was no error prompt this time :)

**Comment by mikfhan** [comment]
Nice! Fingers crossed if nothing else pops up 3.5-release goes public after weekly reset 25th jan.
