### ISSUE TITLE
Possible to add support for off tanks?

### ISSUE THREAD

**Issue by Spherikal** [int3ro/Nameplates_Threat#30]
This is a wonderful addon that fixes (almost) every single issue I got with the default Blizzard UI. My only issue is that when there’s more than one tank it’s hard to know who the job is ranked by.

Are there any plans on adding support to change the color of off-tanks?

**Comment by mikfhan** [comment]
Thanks! Right now if you are tank the color depends on who has aggro for the enemy (other tanks it's gray, on you it's green). I sort of ran out of colors to use, so it's only those two colors I can reuse without a bunch of rework. I might also not be able to change the ruleset if YOU have a tank role.

If you are the healer/damage role it just colors green when any tank has aggro for the enemy. Here I should be able to reuse both colors to give more information, maybe something like this below instead of the above?

Enemy aggroes raid main tank (or party tank who is also group leader): green
Enemy aggroes raid main assist (or party tank who is not group leader): gray

**Comment by Spherikal** [comment]
I see! So if I'm the tank and the other tank has aggro the nameplate is gray? Is the color the same for me?

Because this feature would likely only be useable by tanks (I'm a tank myself). I want to keep track on whether it's me, or my tanking buddy who has aggro at any given moment (so that either me or him can pick up adds that a DPS might've pulled away from us).

Does that make sense?

**Comment by mikfhan** [comment]
Precisely, it SHOULD already color green if you are a tank role and have aggro, but gray if other tanks have it. If you were looking over the shoulder of whoever is playing the other tank, on their screen THEY would show green and you as gray. So you SHOULD already be able to tell yourself from your tanking buddy/buddies just by that, where you two can sort of ignore the green/gray nameplates since either one of you is already tanking those.

Do note if "color gradient" is enabled: you will fade slowly from green toward gray as your threat percentage drops below 100 percent (where you normally lose the aggro to the second in line on the monster's threat table, perhaps your tanking buddy) and back toward green if you regain high threat. Maybe try to disable "color gradient" for a bit then it should be easier to verify your tanking is green and other tanks is gray by the pure colors, then just enable "color gradient" again when ready to use it.

**Comment by mikfhan** [comment]
Alright, I've updated the readme.md now for upcoming 3.5-release, you can see it below:
https://github.com/int3ro/Nameplates_Threat/tree/mikfhan

I assume this issue is then resolved, otherwise do let me know if it's still unclear (especially the bottom three paragraphs).
